job_name: my-cool-app
src_path: /fully/qualifies/location
jenkins_external_port: 8888
jenkins_admin_username: admin
jenkins_admin_password: admin
plugins:
  blueocean
  jclouds-jenkins
  docker-plugin
  copyartifact
  ws-cleanup